

version: '3.12.2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
     
    network_mode: host
    env_file:
      - .env  
    volumes:
      - ./data:/app/data   # Mapping local folder 'data' to container's 'data' folder
